Repository FaculdadeSenaiJoinville/odysseus, pull requests merged in 2021-11, with the labels that each got.

#38 PES-346 - Validação que no nome tenha pelo menos um espaço para obrigar a colocar nome e sobrenome
  jest.config.ts
  package.json
  src/core/error/errors.service.ts
  src/core/error/utils/error.types.ts
  src/core/repository/filters/entity-not-found-exception.filter.ts
  src/modules/user/specs/stubs/user.stubs.ts
  src/modules/user/specs/users.spec.ts
  src/modules/user/users.service.ts
  src/modules/user/utils/users.policies.ts
  yarn.lock
Labels: bug, code review

#40 Renomeando campo users para members
  src/modules/group/group.service.ts
  src/modules/group/utils/group.repository.ts
  src/modules/user/users.service.ts
Labels: code review

#32 PES-316 - Desenvolver o MER
  .env.example
  documentation/chatbot_mysql.mwb
  documentation/chatbot_mysql.mwb.bak
  documentation/mysql.mwb
  documentation/mysql.mwb.bak
  jest.config.ts
  package.json
  scripts/dml/new_mysql_dml.script.ts
  scripts/dml/run_mysql_dml.script.ts
  src/core/database/entities/bot-content.entity.ts
  src/core/database/entities/bot-intent-contents.entity.ts
  src/core/database/entities/bot-intent.entity.ts
  src/core/database/entities/core-entity.entity.ts
  src/core/database/entities/index.ts
  src/core/database/migrations/1634417358060-create_bot_intent_table.ts
  src/core/database/migrations/1635902999135-create_bot_content_table.ts
  src/core/database/migrations/1635903027318-create_bot_intent_contents_table.ts
  src/core/database/scripts/20211011213653_create_master.script.ts
  src/core/repository/mysql/mysql-repository.service.ts
  src/modules/chatbot/chatbot.controller.ts
  src/modules/chatbot/chatbot.module.ts
  src/modules/chatbot/chatbot.service.ts
  src/modules/chatbot/content/content.controller.ts
  src/modules/chatbot/content/content.module.ts
  src/modules/chatbot/content/content.service.ts
  src/modules/chatbot/content/dto/create-content.dto.ts
  src/modules/chatbot/content/utils/bot-content-pagination.pipe.ts
  src/modules/chatbot/content/utils/bot-content.repository.ts
  src/modules/chatbot/content/utils/bot-content.validation.ts
  src/modules/chatbot/dialogflow/dialogflow.module.ts
  src/modules/chatbot/dialogflow/dialogflow.service.ts
  src/modules/chatbot/dialogflow/utils/dialogflow.config.ts
  src/modules/chatbot/dialogflow/utils/dialogflow.types.ts
  src/modules/chatbot/dto/message-data.dto.ts
  src/modules/chatbot/intent/dto/create-intent.dto.ts
  src/modules/chatbot/intent/intent.controller.ts
  src/modules/chatbot/intent/intent.module.ts
  src/modules/chatbot/intent/intent.service.ts
  src/modules/chatbot/intent/utils/bot-intent-pagination.pipe.ts
  src/modules/chatbot/intent/utils/bot-intent.repository.ts
  src/modules/chatbot/intent/utils/bot-intent.validation.ts
  src/modules/chatbot/utils/chatbot.validation.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.module.ts
  src/modules/group/utils/group-pagination.pipe.ts
  src/modules/group/utils/group.helper.ts
  src/modules/group/utils/group.repository.ts
  src/modules/index.ts
  src/modules/user/users.service.ts
  yarn.lock
Labels: feature, code review

#41 PES-354 - Criar bot do telegram
  .env.example
  package.json
  src/modules/chatbot/chatbot.controller.ts
  src/modules/chatbot/chatbot.module.ts
  src/modules/chatbot/chatbot.service.ts
  src/modules/chatbot/intent/utils/bot-intent.validation.ts
  src/modules/chatbot/utils/telegram.config.ts
  yarn.lock
Labels: feature

#42 PES-342 - Tela de login está fazendo uma requisição para "/me"
  package.json
  src/core/error/errors.service.ts
  src/core/repository/mysql/mysql-repository.service.ts
  yarn.lock
Labels: bug

#45 PES-351 - Desenvolvimento Telas
  package.json
  src/core/database/entities/bot-content.entity.ts
  src/core/database/entities/bot-intent.entity.ts
  src/core/database/entities/user.entity.ts
  src/core/database/migrations/1637369363203-update_bot_intent_table.ts
  src/modules/chatbot/dialogflow/dialogflow.service.ts
  src/modules/chatbot/dialogflow/utils/dialogflow.types.ts
  src/modules/chatbot/intent/dto/upsert-intent.dto.ts
  src/modules/chatbot/intent/intent.controller.ts
  src/modules/chatbot/intent/intent.service.ts
  src/modules/chatbot/intent/utils/bot-intent.repository.ts
  src/modules/chatbot/intent/utils/bot-intent.validation.ts
  src/modules/group/dto/upsert-group.dto.ts
  src/modules/group/group.service.ts
  src/modules/group/specs/group.spec.ts
  src/modules/group/utils/group.policies.ts
  src/modules/group/utils/group.repository.ts
  src/modules/group/utils/group.validation.ts
  src/modules/user/dtos/create-user.dto.ts
  src/modules/user/dtos/update-user.dto.ts
  src/modules/user/specs/users.spec.ts
  src/modules/user/users.service.ts
  src/modules/user/utils/users.policies.ts
  src/modules/user/utils/users.validation.ts
  yarn.lock
Labels: feature, code review

#43 PES-314 - Modificar modal de criar/editar/detalhes de usuários
  src/modules/user/dtos/create-user.dto.ts
  src/modules/user/dtos/update-user.dto.ts
  src/modules/user/specs/users.spec.ts
  src/modules/user/users.service.ts
  src/modules/user/utils/users.policies.ts
  src/modules/user/utils/users.validation.ts
Labels: feature, code review

#46 PES-355 - Histórico do chatbot
  src/core/database/entities/bot-content.entity.ts
  src/core/database/entities/bot-history.entity.ts
  src/core/database/entities/index.ts
  src/core/database/migrations/1637541386513-create_bot_histories.ts
  src/modules/chatbot/chatbot.module.ts
  src/modules/chatbot/chatbot.service.ts
  src/modules/chatbot/content/content.service.ts
  src/modules/chatbot/dialogflow/utils/dialogflow.types.ts
  src/modules/chatbot/history/dto/create-history.dto.ts
  src/modules/chatbot/history/history.controller.ts
  src/modules/chatbot/history/history.module.ts
  src/modules/chatbot/history/history.service.ts
  src/modules/chatbot/history/utils/bot-history-pagination.pipe.ts
  src/modules/chatbot/history/utils/bot-history.repository.ts
Labels: feature, code review

#47 PES-356 - Corrigir problemas com content
  src/core/database/migrations/1635902999135-create_bot_content_table.ts
  src/modules/chatbot/content/content.module.ts
  src/modules/chatbot/content/content.service.ts
  src/modules/chatbot/content/utils/bot-content.validation.ts
  src/modules/chatbot/intent/utils/bot-intent.repository.ts
  src/modules/group/utils/group.policies.ts
Labels: feature
